# -*- python -*-
# encoding: utf-8

def configure(conf):
    conf.env.append_value('MODULES_AVAILABLE', 'nautilusburn')
    if 'nautilusburn' in conf.env['ENABLE_MODULES'] or 'all' in conf.env['ENABLE_MODULES']:
        if conf.pkg_check_modules('NAUTILUSBURN',
                                  'libnautilus-burn >= 2.15.3 pygobject-2.0',
                                  mandatory=False):
            conf.env.append_value('MODULES_TO_BUILD', 'nautilusburn')


def build(bld):
    if 'nautilusburn' in bld.env['MODULES_TO_BUILD']:
        bld.codegen('nautilus_burn', prefix='nautilus_burn')
        pyext = bld.create_pyext()
        pyext.source = 'nb_module.c nautilus_burn.c nb_track.c'
        pyext.includes = '.'
        pyext.target = 'nautilusburn'
        pyext.uselib = 'NAUTILUSBURN'
        pyext.install_path = '${PYTHONDIR}/gtk-2.0'

        bld.install_files('${DATADIR}/pygtk/2.0/defs', 'nautilus_burn.defs')

