# -*- python -*-
# encoding: utf-8

def configure(conf):
    conf.env.append_value('MODULES_AVAILABLE', 'gnomeapplet')
    if 'gnomeapplet' in conf.env['ENABLE_MODULES'] or 'all' in conf.env['ENABLE_MODULES']:
        if conf.pkg_check_modules('GNOMEAPPLET',
                                  'libpanelapplet-2.0 >= 2.13.4 pygobject-2.0 libgnome-2.0 libgnomeui-2.0',
                                  mandatory=False):
            conf.env.append_value('MODULES_TO_BUILD', 'gnomeapplet')


def build(bld):
    env = bld.env
    if 'gnomeapplet' in env['MODULES_TO_BUILD']:
        bld.codegen('applet')
        pyext = bld.create_pyext()
        pyext.source = 'appletmodule.c applet.c'
        pyext.target = 'gnomeapplet'
        pyext.uselib = 'GNOMEAPPLET'
        pyext.install_path = '${PYTHONDIR}/gtk-2.0'

        bld.install_files('${DATADIR}/pygtk/2.0/defs', 'applet.defs')

