# -*- python -*-
# encoding: utf-8

import os
import Common

def configure(conf):
    conf.env.append_value('MODULES_AVAILABLE', 'mediaprofiles')
    if 'mediaprofiles' in conf.env['ENABLE_MODULES'] or 'all' in conf.env['ENABLE_MODULES']:
        if conf.check_pkg('gnome-media-profiles >= 2.10.0 pygobject-2.0 ',
                          destvar='MEDIAPROFILES', mandatory=False):
            conf.env.append_value('MODULES_TO_BUILD', 'mediaprofiles')


def codegen(bld, module):
    cmd = bld.create_obj('command-output')
    cmd.command = bld.env()['CODEGEN']
    cmd.command_is_external = True
    cmd.prio = 5
    cmd.argv = [
        '--py_ssize_t-clean',
        '--register', os.path.join(cmd.env['PYGTK_DEFSDIR'], 'pango-types.defs'),
        '--register', os.path.join(cmd.env['PYGTK_DEFSDIR'], 'gdk-types.defs'),
        '--register', os.path.join(cmd.env['PYGTK_DEFSDIR'], 'gtk-types.defs'),
        '--prefix', 'py'+module,
        '--override', cmd.input_file("%s.override" % module),
        cmd.input_file("%s.defs" % module),
        ]
    cmd.stdout = '%s.c' % module
    return cmd


def build(bld):
    
    if 'mediaprofiles' in bld.env()['MODULES_TO_BUILD']:
        codegen(bld, 'mediaprofiles')
        pyext = bld.create_pyext()
        pyext.source = 'mediaprofilesmodule.c mediaprofiles.c'
        pyext.target = 'mediaprofiles'
        pyext.uselib = 'MEDIAPROFILES'
        pyext.inst_var = 'PYTHONDIR'
        pyext.inst_dir = 'gtk-2.0'

        defsdir = Common.install_files('DATADIR', os.path.join('pygtk', '2.0', 'defs'),
                                       ['mediaprofiles.defs'])

